In [2]:
import pandas as pd
import numpy as np
from datetime import datetime

In [7]:
#Load Data
df = pd.read_csv(r"D:\DataAnalysis\Projects\Sales Analytics\data\SampleSuperstore.csv", encoding = 'latin1' )

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [9]:
#Basic Cleaning

df['Order Date'] = pd.to_datetime(df['Order Date'], format='%m/%d/%Y')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%m/%d/%Y')
df = df.drop_duplicates()
df = df.dropna(subset=['Sales','Profit'])  # we can handle here as per business rule

In [10]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [11]:
#Feature Engineering

df['Profit Margin'] = (df['Profit'] / df['Sales']) * 100
df['Shipping Days'] = (df['Ship Date'] - df['Order Date']).dt.days

In [14]:

#RFM Segmentation (Gold for MNC's!)

latest_date = df['Order Date'].max()
rfm = df.groupby('Customer ID').agg({
    'Order Date': lambda x: (latest_date - x.max()).days,
    'Order ID':'nunique',
    'Sales': 'sum'

}).rename(columns= {'Order Date': 'Recency', 'Order ID':'Frequency','Sales':'Monetary'})

In [15]:
rfm

             Recency  Frequency  Monetary
Customer ID
AA-10315         184          5  5563.560
AA-10375          19          9  1056.390
AA-10480         259          4  1790.512
AA-10645          55          6  5086.935
AB-10015         415          3   886.156
...              ...        ...       ...
XP-21865          43         11  2374.658
YC-21895           4          5  5454.350
YS-21880           9          8  6720.444
ZC-21910          54         13  8025.707
ZD-21925         202          5  1493.944

[793 rows x 3 columns]

In [17]:
#Scoring (1-5 scale)
rfm['R_Score'] = pd.qcut(rfm['Recency'],5,labels = [5,4,3,2,1])
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'),5,labels=[1,2,3,4,5])
rfm['M_Score'] = pd.qcut(rfm['Monetary'],5,labels=[1,2,3,4,5])
rfm['RFM_Score']  = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str) + rfm['M_Score'].astype(str)

In [23]:
# Export for power BI
rfm.to_csv(r'D:\DataAnalysis\Projects\Sales Analytics\data\rfm_segmented.csv')
df.to_csv(r'D:\DataAnalysis\Projects\Sales Analytics\data\cleaned_superstore.csv', index=False)

print(rfm['RFM_Score'].value_counts().head(10))

RFM_Score
111    39
555    22
112    18
245    18
455    17
433    15
511    15
121    14
454    14
344    14
Name: count, dtype: int64